"""Tests for the civic dashboard service and export formatting."""

from unittest.mock import AsyncMock, patch

import pytest

from app.services.dashboard_service import format_export_text


class TestDashboardExportFormat:
    """Verify the export text matches the spec character-for-character."""

    def test_export_format_matches_spec(self):
        """Happy path: verify exact export text output."""
        snapshot = {
            "period_start": "2026-05-14",
            "period_end": "2026-06-13",
            "total_posts": 47,
            "emergency_posts": 18,
            "resolved_posts": 11,
            "category_breakdown": {
                "power": 22,
                "security": 9,
                "infrastructure": 7,
                "water": 4,
                "general": 5,
            },
        }
        result = format_export_text(snapshot, "Green Valley Housing Society", "Karachi")
        expected = (
            "Halqa Neighborhood Intelligence Report\n"
            "Green Valley Housing Society — Karachi\n"
            "Period: 2026-05-14 to 2026-06-13\n"
            "\n"
            "Summary:\n"
            "• 47 community reports submitted\n"
            "• 18 emergency alerts raised\n"
            "• 11 issues resolved\n"
            "\n"
            "Reports by type:\n"
            "• Power/Electricity: 22\n"
            "• Security: 9\n"
            "• Infrastructure: 7\n"
            "• Water: 4\n"
            "• General: 5\n"
            "\n"
            "Generated by Halqa — halqa.app\n"
            "This report represents aggregated, anonymized community data.\n"
            "Individual reporter identities are not disclosed.\n"
        )
        assert result == expected, f"Export format mismatch:\nExpected:\n{expected}\n\nGot:\n{result}"

    def test_export_format_no_city(self):
        """Edge: city omitted — " — City" suffix should not appear."""
        snapshot = {
            "period_start": "2026-05-14",
            "period_end": "2026-06-13",
            "total_posts": 5,
            "emergency_posts": 2,
            "resolved_posts": 1,
            "category_breakdown": {
                "power": 3,
                "security": 0,
                "infrastructure": 0,
                "water": 1,
                "general": 1,
            },
        }
        result = format_export_text(snapshot, "Test Colony")
        lines = result.strip().split("\n")
        assert lines[1] == "Test Colony", f"Expected line 2 to be just name, got '{lines[1]}':\n{result}"

    def test_export_format_empty_breakdown(self):
        """Edge: empty category breakdown — all categories show 0."""
        snapshot = {
            "period_start": "2026-01-01",
            "period_end": "2026-01-31",
            "total_posts": 0,
            "emergency_posts": 0,
            "resolved_posts": 0,
            "category_breakdown": {},
        }
        result = format_export_text(snapshot, "Empty Town")
        for cat_label in ("Power/Electricity", "Security", "Infrastructure", "Water", "General"):
            assert f"• {cat_label}: 0" in result, f"Missing '{cat_label}: 0' line"

    def test_export_format_breakdown_missing_keys(self):
        """Edge: missing category keys in breakdown — defaults to 0."""
        snapshot = {
            "period_start": "2026-01-01",
            "period_end": "2026-01-31",
            "total_posts": 3,
            "emergency_posts": 1,
            "resolved_posts": 1,
            "category_breakdown": {"power": 2, "security": 1},
        }
        result = format_export_text(snapshot, "Partial Town")
        assert "• Power/Electricity: 2" in result
        assert "• Security: 1" in result
        assert "• Infrastructure: 0" in result
        assert "• Water: 0" in result
        assert "• General: 0" in result


class TestDashboardService:
    """Tests for get_or_compute_snapshot and compute logic."""

    @pytest.mark.asyncio
    async def test_get_or_compute_returns_existing_snapshot(self, mock_db, sample_neighborhood_id):
        """Happy path: existing snapshot is enriched and returned."""
        fake_snapshot = {
            "id": "snap-1",
            "neighborhood_id": str(sample_neighborhood_id),
            "period_type": "30d",
            "period_start": "2026-05-14",
            "period_end": "2026-06-13",
            "total_posts": 47,
            "emergency_posts": 18,
            "resolved_posts": 11,
            "active_members": 28,
            "category_breakdown": {"power": 22, "security": 9, "infrastructure": 7, "water": 4, "general": 5},
            "computed_at": "2026-06-13T12:00:00+00:00",
        }

        with patch("app.services.dashboard_service.dashboard_repo.get_latest", new_callable=AsyncMock) as mock_get, \
                patch("app.services.dashboard_service.get_neighborhood", new_callable=AsyncMock) as mock_hood:

            mock_get.return_value = fake_snapshot
            mock_hood.return_value = {"name": "Green Valley Housing Society", "city": "Karachi"}

            from app.services.dashboard_service import get_or_compute_snapshot
            result = await get_or_compute_snapshot(mock_db, sample_neighborhood_id, "30d")

            assert result["neighborhood_name"] == "Green Valley Housing Society"
            assert result["total_posts"] == 47
            assert result["category_breakdown"]["power"] == 22
            mock_get.assert_called_once_with(mock_db, sample_neighborhood_id, "30d")
            mock_hood.assert_called_once_with(mock_db, sample_neighborhood_id)

    @pytest.mark.asyncio
    async def test_compute_empty_neighborhood(self, mock_db, sample_neighborhood_id):
        """Edge: neighborhood with no posts — returns zero counts."""
        with patch("app.services.dashboard_service.dashboard_repo.get_latest", new_callable=AsyncMock) as mock_get, \
                patch("app.services.dashboard_service.get_neighborhood", new_callable=AsyncMock) as mock_hood, \
                patch("app.services.dashboard_service.dashboard_repo.create_snapshot", new_callable=AsyncMock) as mock_create:

            mock_get.return_value = None
            mock_hood.return_value = {"name": "Empty Estates", "city": ""}

            async def fake_create_snapshot(*_args, **_kwargs):
                return {
                    "period_type": "7d",
                    "total_posts": 0,
                    "emergency_posts": 0,
                    "resolved_posts": 0,
                    "active_members": 0,
                    "category_breakdown": {},
                    "period_start": "2026-06-06",
                    "period_end": "2026-06-13",
                    "computed_at": "2026-06-13T12:00:00+00:00",
                    "neighborhood_id": str(sample_neighborhood_id),
                }

            mock_create.side_effect = fake_create_snapshot

            async def fake_fetch(*_args, **_kwargs):
                return []

            with patch("app.services.dashboard_service.asyncio.to_thread", side_effect=fake_fetch):
                from app.services.dashboard_service import compute_snapshot
                result = await compute_snapshot(mock_db, sample_neighborhood_id, "7d")

                assert result["total_posts"] == 0
                assert result["emergency_posts"] == 0
                assert result["resolved_posts"] == 0
                assert result["active_members"] == 0
                assert result["category_breakdown"]["power"] == 0
                assert result["neighborhood_name"] == "Empty Estates"


class TestDashboardExportLines:
    """Verify specific structural elements in the export."""

    def test_export_has_title(self):
        snapshot = {
            "period_start": "2026-06-01",
            "period_end": "2026-06-13",
            "total_posts": 1,
            "emergency_posts": 0,
            "resolved_posts": 1,
            "category_breakdown": {"general": 1},
        }
        text = format_export_text(snapshot, "Test", "City")
        assert text.startswith("Halqa Neighborhood Intelligence Report\n")
        assert "Generated by Halqa — halqa.app" in text
        assert "Individual reporter identities are not disclosed." in text
