"""Civic dashboard computation and export business logic."""

import logging
from datetime import datetime, timedelta
from uuid import UUID

logger = logging.getLogger(__name__)


# async def get_or_compute_snapshot(db, neighborhood_id: UUID, period_days: int) -> dict:
#     """Get the latest dashboard snapshot or compute one on demand."""
#     from app.repositories import dashboard_repo, post_repo
#     snapshot = await dashboard_repo.get_latest(db, neighborhood_id, period_days)
#     if snapshot:
#         return snapshot
#     return await compute_snapshot(db, neighborhood_id, period_days)


# async def compute_snapshot(db, neighborhood_id: UUID, period_days: int) -> dict:
#     """Compute a dashboard snapshot from post data."""
#     from app.repositories import dashboard_repo, post_repo
#     from_date = (datetime.utcnow() - timedelta(days=period_days)).isoformat()
#     posts = await post_repo.get_for_dashboard(db, neighborhood_id, from_date)
#     counts = {
#         "total_posts": len(posts),
#         "emergency_count": sum(1 for p in posts if p.get("is_emergency")),
#         "resolved_count": sum(1 for p in posts if p.get("is_resolved")),
#         "power_count": sum(1 for p in posts if p.get("category") == "power"),
#         "security_count": sum(1 for p in posts if p.get("category") == "security"),
#         "infrastructure_count": sum(1 for p in posts if p.get("category") == "infrastructure"),
#         "water_count": sum(1 for p in posts if p.get("category") == "water"),
#         "general_count": sum(1 for p in posts if p.get("category") == "general"),
#     }
#     return await dashboard_repo.create_snapshot(db, neighborhood_id, period_days, counts)


# def format_dashboard_export(snapshot: dict, neighborhood_name: str) -> str:
#     """Format dashboard data as a plain-text export ready for sharing with utility providers."""
#     period_label = {7: "Last 7 days", 30: "Last 30 days", 90: "Last 3 months"}
#     return "\n".join([
#         "HALQA NEIGHBORHOOD REPORT",
#         neighborhood_name,
#         f"Period: {period_label.get(snapshot['period_days'], '')}",
#         f"Generated: {snapshot.get('snapshot_date', '')}",
#         "",
#         "SUMMARY",
#         f"Total incidents reported: {snapshot['total_posts']}",
#         f"Resolved: {snapshot['resolved_posts']} ({int(snapshot['resolved_posts'] / max(snapshot['total_posts'], 1) * 100)}%)",
#         "",
#         "BREAKDOWN",
#         f"Power outages:    {snapshot['power_count']}  ({snapshot.get('power_resolved', 0)} resolved)",
#         f"Security:         {snapshot['security_count']}  ({snapshot.get('security_resolved', 0)} resolved)",
#         f"Infrastructure:   {snapshot['infrastructure_count']}  ({snapshot.get('infrastructure_resolved', 0)} resolved)",
#         f"Water:            {snapshot['water_count']}  ({snapshot.get('water_resolved', 0)} resolved)",
#         f"General:          {snapshot['general_count']}  (0 resolved)",
#         "",
#         "This report was generated by Halqa (halqa.pk).",
#         "For questions, contact your neighborhood anchor.",
#     ])
