"use client";

import { useState, useCallback } from "react";
import { cn } from "@/lib/utils";
import { ShieldCheck, CheckCircle, CopySimple, FilePdf } from "@phosphor-icons/react";

interface ExportCardProps {
  neighborhoodId: string;
  periodType: string;
  neighborhoodName: string;
  city: string;
  snapshotData: {
    period_start: string;
    period_end: string;
    total_posts: number;
    emergency_posts: number;
    resolved_posts: number;
    category_breakdown: Record<string, number>;
  };
  className?: string;
}

export function ExportCard({
  neighborhoodId: _neighborhoodId,
  periodType: _periodType,
  neighborhoodName,
  city,
  snapshotData,
  className,
}: ExportCardProps) {
  const [copied, setCopied] = useState(false);
  const [showPdfToast, setShowPdfToast] = useState(false);

  const buildExportText = useCallback(() => {
    const cat = snapshotData.category_breakdown ?? {};
    return [
      "Halqa Neighborhood Intelligence Report",
      `${neighborhoodName}${city ? ` \u2014 ${city}` : ""}`,
      `Period: ${snapshotData.period_start} to ${snapshotData.period_end}`,
      "",
      "Summary:",
      `\u2022 ${snapshotData.total_posts} community reports submitted`,
      `\u2022 ${snapshotData.emergency_posts} emergency alerts raised`,
      `\u2022 ${snapshotData.resolved_posts} issues resolved`,
      "",
      "Reports by type:",
      `\u2022 Power/Electricity: ${cat.power ?? 0}`,
      `\u2022 Security: ${cat.security ?? 0}`,
      `\u2022 Infrastructure: ${cat.infrastructure ?? 0}`,
      `\u2022 Water: ${cat.water ?? 0}`,
      `\u2022 General: ${cat.general ?? 0}`,
      "",
      "Generated by Halqa \u2014 halqa.app",
      "This report represents aggregated, anonymized community data.",
      "Individual reporter identities are not disclosed.",
    ].join("\n");
  }, [neighborhoodName, city, snapshotData]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(buildExportText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Silently fail if clipboard API is unavailable
    }
  }, [buildExportText]);

  const handlePdf = useCallback(() => {
    setShowPdfToast(true);
    setTimeout(() => setShowPdfToast(false), 2000);
  }, []);

  return (
    <div className={cn("rounded-lg bg-halqa-teal-light p-4", className)}>
      <div className="flex items-start gap-3">
        <ShieldCheck
          size={20}
          className="shrink-0 mt-0.5 text-halqa-teal"
        />
        <p className="text-sm text-halqa-ink-mid">
          Share this report with WAPDA, your union council, or municipal
          authorities.
        </p>
      </div>

      <div className="mt-4 flex flex-col gap-2">
        <button
          type="button"
          onClick={handleCopy}
          className="flex w-full items-center justify-center gap-2 rounded-lg bg-halqa-teal px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-halqa-teal-dark"
        >
          {copied ? (
            <>
              <CheckCircle size={18} weight="fill" />
              Copied to clipboard
            </>
          ) : (
            <>
              <CopySimple size={18} />
              Copy report text
            </>
          )}
        </button>

        <button
          type="button"
          onClick={handlePdf}
          className="flex w-full items-center justify-center gap-2 rounded-lg border border-halqa-sand-dark px-4 py-2.5 text-sm font-semibold text-halqa-ink-mid transition-colors hover:bg-halqa-sand"
        >
          <FilePdf size={18} />
          Download as PDF
        </button>

        {showPdfToast && (
          <p className="text-center text-xs text-halqa-ink-light">
            PDF export coming soon
          </p>
        )}
      </div>
    </div>
  );
}
